apiVersion: apps/v1                          
kind: Deployment                             
metadata:
  name: miriam-bd                     
  labels:
    app: datos                             
spec:
  selector:                                  
    matchLabels:                              
      app: datos
      tier: dos
  replicas: 1                                 
  template:                                  
    metadata:
      labels:
        app: datos                           
        tier: dos                             
    spec:
      containers:                             
      - name: db-img                       
        image: miriamak/db-img:v1    
        env:
        - name: MYSQL_ROOT_PASSWORD          
          value: root
        - name: MYSQL_DATABASE                
          value: crud
        - name: MYSQL_USER
          value: miriam
        - name: MYSQL_PASSWORD
          value: miriam123
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:                                
        - containerPort: 3306
        volumeMounts:                       
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-claim
