apiVersion: v1                 
kind: Service                    
metadata:
  name: miriam-service              
  labels:                        
    app: datos                   
    tier: dos
spec:
  type : NodePort
  ports:                        
  - port: 3306
    protocol: TCP
  selector:                      
    app: datos
    tier: dos
