apiVersion: v1
kind: Service
metadata:
  name: miriam-servicio-crud
  labels:
    app: correos
    tier: uno
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: correos
    tier: uno